[package]
name = "rust-gen-eth-rator"
version = "0.1.0"
edition = "2024"
authors = ["Leo Sagan"]

[dependencies]
bip39 = "1.2"
ethers = "2.0.14"
anyhow = "1.0"
hex = "0.4"
rand = "0.8"
rand_core = "0.6"